<?php

namespace BookBundle\Repository;

/**
 * EditorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorsRepository extends \Doctrine\ORM\EntityRepository
{
}
