services:
#    actu_article.example:
#        class: Actu\ArticleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  # ArticleBundle\DataFixtures\:
  #   ressource: '../../DataFixtures'
  #   tags: ['doctrine.fixture.orm']
  # _defaults:
  #   autowire: true
  #   autoconfigure: true
  #   public: false